version: '3.8'
services:
    app:
        build: .
        container_name: job-portal-app
        restart: always
        env_file:
            - .env
        ports:
            - '5000:5000'
        volumes:
            - .:/usr/src/app
        depends_on:
            - db
    db:
        image: postgres:14
        container_name: job-portal-db
        restart: always
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        ports:
            - '5433:5432'
        volumes:
            - db_data:/var/lib/postgresql/data
            - ./config/init.sql:/docker-entrypoint-initdb.d/init.sql
    nginx:
        image: nginx:latest
        container_name: job-portal-nginx
        restart: always
        ports:
            - '8080:8080'
            - '8443:8443'
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./certs:/etc/nginx/certs:ro
        depends_on:
            - app
volumes:
    db_data:
